# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/ProviderNameLowercase/ci.mgmt.yml
    - sdk/ProviderNameLowercase/Azure.ResourceManager.Cost_Management/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: ProviderNameLowercase
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.Cost_Management
      safeName: AzureResourceManagerCost-Management
