# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/analyzeconversations
    - sdk/analyzeconversations/ci.yml
    - sdk/analyzeconversations/Azure.AI.Language.Authoring.Analyzeconversations

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/analyzeconversations
    - sdk/analyzeconversations/ci.yml
    - sdk/analyzeconversations/Azure.AI.Language.Authoring.Analyzeconversations

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: analyzeconversations
    ArtifactName: packages
    Artifacts:
    - name: Azure.AI.Language.Authoring.Analyzeconversations
      safeName: AzureAILanguageAuthoringAnalyzeconversations
